# Generated by Django 3.2.2 on 2021-05-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='template_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PYTHON', 'PYTHON'), ('PHP', 'PHP PATNERS'), ('JAVA', 'JAVA'), ('MERN', 'MERN'), ('MEAN', 'MEAN')], max_length=12)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('is_pro', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
